apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: jaeger
namespace: observability

resources:
- https://github.com/jaegertracing/jaeger-operator/releases/download/v1.53.0/jaeger-operator.yaml